# Generated by Django 4.0.3 on 2022-03-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('adres', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('zip_code', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
            ],
        ),
    ]
