# Generated by Django 4.0.3 on 2022-03-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=255)),
                ('persons', models.CharField(max_length=60)),
                ('preperation_time', models.CharField(max_length=25)),
            ],
        ),
    ]
