# Generated by Django 4.0.3 on 2022-03-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recept'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
